[tool.poetry]
name = "pyhton-sapling"
version = "0.1.0"
description = ""
authors = ["edmamerto"]
readme = "README.md"
packages = [{include = "pyhton_sapling"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
